#!/usr/bin/env python3
"""
Validate integration docs against platform official documentation.
For each integration page, extracts the platform docs URL and generates
a claude CLI command to run the validation.

Usage: python3 validate-integration-docs.py
Output: validation-report.md in the same directory
"""

import os
import re
from pathlib import Path

INTEGRATIONS_DIR = Path(__file__).parent.parent / "guide" / "integrations"
REPORT_FILE = Path(__file__).parent / "validation-report.md"

PICSART_DOMAINS = {"picsart.com", "picsart.github.io", "mcp.picsart.io"}

def extract_platform_docs_url(content: str) -> str | None:
    urls = re.findall(r'https?://[^\s\)\"\']+', content)
    for url in urls:
        domain = re.sub(r'^https?://', '', url).split('/')[0]
        if domain not in PICSART_DOMAINS:
            return url.rstrip('.,)')
    return None

def extract_title(content: str) -> str:
    for line in content.splitlines():
        if line.startswith('# '):
            return line[2:].strip()
    return "Unknown"

def build_validation_prompt(title: str, page_path: str, docs_url: str) -> str:
    return (
        f"You are validating Picsart MCP integration documentation for {title}. "
        f"Read the integration page at {page_path} and the official platform documentation at {docs_url}. "
        f"Check: (1) Are the setup steps accurate and complete? "
        f"(2) Are config file paths and JSON/YAML structure correct? "
        f"(3) Are any auth/header field names wrong? "
        f"(4) Is anything in our docs contradicted by the official docs? "
        f"(5) Are there important steps in the official docs that we omitted? "
        f"Report issues as a numbered list. If everything is accurate, say 'PASS'."
    )

def main():
    pages = sorted(INTEGRATIONS_DIR.glob("*.md"))
    pages = [p for p in pages if p.name != "index.md"]

    report_lines = [
        "# Integration Docs Validation Report",
        "",
        f"Generated by validate-integration-docs.py",
        f"Integrations checked: {len(pages)}",
        "",
        "---",
        "",
    ]

    for page in pages:
        content = page.read_text()
        title = extract_title(content)
        docs_url = extract_platform_docs_url(content)
        rel_path = f"guide/integrations/{page.name}"

        report_lines.append(f"## {title}")
        report_lines.append("")

        if docs_url:
            prompt = build_validation_prompt(title, rel_path, docs_url)
            claude_cmd = f'claude -p "{prompt}"'
            report_lines.append(f"**Platform docs:** {docs_url}")
            report_lines.append("")
            report_lines.append("**Validation command:**")
            report_lines.append("```bash")
            report_lines.append(claude_cmd)
            report_lines.append("```")
        else:
            report_lines.append("**Platform docs:** not found in page — add an official docs link to enable validation.")

        report_lines.append("")
        report_lines.append("---")
        report_lines.append("")

    REPORT_FILE.write_text("\n".join(report_lines))
    print(f"Report written to {REPORT_FILE}")
    print(f"Checked {len(pages)} integration pages.")

if __name__ == "__main__":
    main()
